# Pandas 入门

Pandas  经常和其他数值计算工具一起使用, 并支持大部分  Numpy  风格的数组计算.

Pandas  虽然采用了很多  Numpy  风格的代码, 但是  pandas  主要是用来处理异质型数据的, 而  Numpy  适合处理同质型数据.

以下为约定俗成的常用导入方式:

In [1]:
import pandas as pd
from pandas import Series, DataFrame

import numpy as np

## Pandas  数据结构

学习  Pandas  需要熟悉两个常用的工具数据结构:  Series  和  DataFrame  .

### Series

Series  是一种一维的数组型对象, 它包含一个值序列, 并包含数据标签, 称为索引.

简单的序列可以仅仅由一个数组形成.

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

如果不为数据指定索引, 那么默认生成的索引是从  0  到  N-1  .

可以通过  `values`  属性和  `index`  属性分别获得  Series  对象的值和索引:

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

通常需要创建一个索引序列, 用标签去标识每个数据点:

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

这时, 你可以像字典一样, 使用标签去索引:

In [6]:
obj2['a']

-5

In [7]:
obj2['d'] = 6

你也可以使用索引列表:

In [8]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

同时也支持  Numpy  风格的数组操作. 同时这些操作会保留索引值的连接.

In [9]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [10]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [11]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

你也可以把  Series  当作字典类型使用, 因为本质上是非常相似的:

In [12]:
'b' in obj2

True

In [13]:
'e' in obj2

False

如果你已经有了一个用字典存储的数据, 那就可以使用字典生成一个  Series  :

In [14]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

如果直接传送一个字典进去, 那么  Series  会自动根据字典序来排列键值对. 如果你不希望排序, 那么可以传入一个数组, 让其生成一个符合预期的  Series  .

In [15]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

需要注意上面那个例子:

1. 其中只有  3  个值被正确放置了.
2. 因为字典中并没有  `California`  , 所以生成的  Series  中  `California`  对应的值是  `NaN`  .
3. 因为传入的序列中, 没有给出  `Utah`  这个键值, 所有这个值没有在  Series  中出现

在  Pandas  中, 使用  `isnull`  和  `notnull`  来检查缺失的数据:

In [16]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

你也可以在实例中直接调用这个两个函数:

In [18]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

自动对齐索引是  Series  中一个非常有用的特性:

In [19]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [20]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series  对象和索引都有  `name`  属性:

In [22]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Series  的索引可以通过一个列表, 按位置进行改变:

In [23]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [24]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

DataFrame  表示的是矩阵的数据表, 它包含已排序的列集合, 每一列可以是不同的值.

DataFrame  既有行索引, 也有列索引. 数据被存储成一个以上的二维块.

虽然  DataFrame  是二维的, 但可以利用分层索引展现更高维的数据.

构建  DataFrame  最常见的方式是利用包含相等长度的列表或者  Numpy  数组的字典来形成  DataFrame  :

In [25]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

DataFrame  会自动为  Series  分配索引.

In [26]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

使用  `head()`  方法可以直选出头部的  5  行:

In [27]:
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

也可以使用列表指定列的顺序:

In [28]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

如果传进去的列在字典中不存在, 那么会用缺失值来填充:

In [29]:
frame2 = pd.DataFrame(data, 
                      columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

你可以通过字典的方式或者属性来检索  Series  :

In [30]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [31]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

返回的  Series  与原  DataFrame  有相同的索引, 且  Series  的  name  属性也会被合理地设置.

行索引则可以通过位置或者属性  `loc`  进行选取:

In [32]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

列的值可以修改, 修改的方式可以参考  Numpy  数组的广播, 亦可以是标量, 亦可以是数组:

In [33]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [34]:
frame2.debt = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

放你想把列表或者数组赋值给一个列时, 必须保证长度和  DataFrame  的长度相匹配.

如果你将一个  Series  赋给一列, Series  索引将会按照  DataFrame  的索引重新排列, 并在空缺的地方填充缺失值:

In [35]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2.debt = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

如果被赋值的列并不存在, 则会生成一个新的列:

In [36]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

可以使用  del  方法移除列:

In [37]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

对  DataFrame  的选取出来的  Series  是视图而不是拷贝, 对  Series  的修改会映射到  DataFrame  中.

如果需要拷贝, 需要显式地调用  `copy()`  方法.

另一种常见的数据形式是嵌套字典:

In [38]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
       'Ohio'  : {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

可以使用类似  Numpy  的语法进行转置:

In [39]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

与之前一样, 如果显式指明索引, 内部字典的键不会被排序:

In [40]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

也可使用包含  Series  的字典构造:

In [41]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

可以向  DataFrame  构造函数传递的对象列表见下表:

如果索引和列拥有  name  属性, 那么这些  name  属性也会被显示:

In [42]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

使用  values  属性可以将数据以二维的  ndarray  的形式返回:

In [43]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

如果他们之间是不同的  dtypes  , 那么会自动选择最适合的  dtypes

In [44]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 索引对象

pandas  中的索引对象适用于存储轴标签和其他元数据的.

在构造  Series  或者  DataFrame  时, 你所以使用的任意数组或者序列都可以在内部转换为索引对象:

In [45]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index= obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [46]:
index[1:]

Index(['b', 'c'], dtype='object')

索引对象是不可表的, 用户无法修改索引对象:

In [47]:
# index[1] = 'd'
# TypeError

不变性是的在多种数据结构中分享索引对象更安全:

In [48]:
labels= pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [49]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [50]:
obj2.index is labels

True

除了类似数组, 索引对象也像一个固定大小的集合:

In [51]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [52]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [53]:
'Ohio' in frame3.columns

True

In [54]:
2003 in frame3.index

False

与  Python  的集合不同, pandas  对象可以包含重复标签:

In [55]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

索引对象一些常用的属性和方法表格:

## 基本功能


Series  和  DataFrame  中数据交互的基础机制。

### 重建索引

`reindex`  是  pandas  对象的重要方法, 用于创建一个符合新索引的新对象:

In [56]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], 
                index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Series  调用  `reindex`  方法时, 会将数据按照新的索引进行排列.

如果某个索引值之前并不存在, 则会引入缺失值来占位:

In [57]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

在重建索引时可能需要插值或者填值, `method`  可选参数允许我们使用诸如  `ffill`  等方法在重建索引时插值, `ffill`  方法会将值向前填充.

In [58]:
obj3 = pd.Series(['bule', 'purple', 'yellow'], 
                 index=[0, 2, 4])
obj3

0      bule
2    purple
4    yellow
dtype: object

In [59]:
obj3.reindex(range(6), method='ffill')

0      bule
1      bule
2    purple
3    purple
4    yellow
5    yellow
dtype: object

在  DataFrame  中, `reindex`  可以改变行索引, 列索引, 也可以同时改变二者.

当只传入一个序列时, 结果中的行会重建索引:

In [60]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                     index=['a', 'c', 'd'], 
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [61]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

使用  `columns`  可以重建列索引:

In [62]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

可以使用  loc  进行更简洁的标签索引:

In [63]:
frame.loc[['a', 'b', 'c', 'd'], states]


/home/hyong/miniconda3/envs/data-ana/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

`reindex`  方法的参数：

### 按轴删除条目

`drop`  方法可以返回对应的标签删除后的新结果:

In [64]:
obj = pd.Series(np.arange(5.), 
                index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [65]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [66]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

在  DataFrame  中, 索引值可以根据轴来删除.

In [67]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                    index=['Ohio', 'Colorado', 'Utah', 'New York'], 
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

默认情况下不指定时, `drop`  根据行标签删除条目:

In [68]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

同时可以通过  `axis=1`  或者  `axis=columns`  来删除列值:

In [69]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [70]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

当指定了参数  inplace  之后, `drop`  就会改变原对象, 不返回新对象.

In [71]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 索引、选择与过滤

Series  的索引与  Numpy  数组索引的功能类似, 只不过  Series  的索引值可以不是整数.

In [72]:
obj = pd.Series(np.arange(4.), 
                index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [73]:
obj['b']

1.0

In [74]:
obj[1]

1.0

In [75]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [76]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [77]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [78]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

Python  中的切片不含尾部, 但  Series  的切片不同:

In [79]:
obj['b': 'c']

b    1.0
c    2.0
dtype: float64

如果切片没有使用整数值, 那么切片结果是包含尾部的

Series  同样支持切片赋值:

In [80]:
obj['b': 'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

DataFrame  的索引也类似:

In [81]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                    index=['Ohio', 'Colorabo', 'Utah', 'New York'], 
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorabo    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [82]:
data['two']

Ohio         1
Colorabo     5
Utah         9
New York    13
Name: two, dtype: int64

In [83]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorabo      6    4
Utah         10    8
New York     14   12

行选择语法与布尔表达式:

In [84]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorabo    4    5      6     7

In [85]:
data[data['three'] > 5]

one  two  three  four
Colorabo    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

布尔表达式索引:

In [86]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorabo   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [87]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorabo    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### 使用 `loc` 和 `iloc` 选择数据

`loc`  轴标签, `iloc`  参数标签

可以利用这两个特殊索引符号以  Numpy  的风格去除数组的行列子集:

In [88]:
# data
data.loc['Colorabo', ['two', 'three']]

two      5
three    6
Name: Colorabo, dtype: int64

In [89]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [90]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [91]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorabo     7    0    5
Utah        11    8    9

同时也可以用于切片:

In [92]:
data.loc[:'Utah', 'two']

Ohio        0
Colorabo    5
Utah        9
Name: two, dtype: int64

In [93]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorabo    0    5      6
Utah        8    9     10
New York   12   13     14

DataFrame  索引选项表:

### 整数索引

pandas  对象在使用整数索引的时候对新用户来说经常会产生歧义, 因为与  Python  内建的数据结构索引有所不同.

比如:

In [94]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

此时索引  -1  , pandas  不知道你到底是像索引  -1  还是  '-1'  ,  然后报错

假如使用非整数索引, 就不会有潜在的歧义:

In [95]:
# ser[-1]
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

基于这种情况, 如果你的数据包含整数的轴索引, 请始终使用标签索引.

或者使用更精确的  `loc`  和  `iloc`  区分两种索引:

In [96]:
ser[:1]

0    0.0
dtype: float64

In [97]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [98]:
ser.iloc[:1]

0    0.0
dtype: float64

### 算术和数据对齐

当你将对象相加时, 如果存在某个索引对不相同时, 则返回结果的索引将是索引对的并集.

In [99]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], 
               index=['a', 'c', 'd', 'e'])
s2 = pd.Series([2.1, 3.6, -1.5, 4, 3.1], 
               index=['a', 'c', 'e', 'f', 'g'])

In [100]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [101]:
s2

a    2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [102]:
s1 + s2

a    9.4
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

在没有重叠的标签位置上, 运算导致了其值为缺失值.

在  DataFrame  上, 行和列都会执行类似的对齐:

In [103]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                   columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                   columns=list('bde'), 
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [104]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [105]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [106]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

如果行列完全不相同, 那么结果将全部为空:

In [107]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [108]:
df1

A
0  1
1  2

In [109]:
df2

B
0  3
1  4

In [110]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

#### 使用填充值的算术方法

应对当产生缺失值时怎么替换缺失值, 变成需要的值.

In [111]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), 
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), 
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan

In [112]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [113]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [114]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

此时在  `fill_value`  参数上, 提供出现缺失值时的值:

In [115]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

类似算数方法之类前面带  r  前缀的都是翻转版的函数:

In [116]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [117]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

重建索引也可能产生控制, 这是也可以利用这个参数自动指定一个值:

In [118]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

算术方法表:

#### DataFrame  和  Series  之间的操作

类似  Numpy  广播风格的算术运算:

In [119]:
arr = np.arange(12.).reshape((3, 4))

In [120]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [121]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [122]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

在  DataFrame  中这个也是类似的:

In [123]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                     columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [124]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [125]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [126]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

如果索引值不在  DataFrame  的列中, 也不再  Series  的索引中, 那么会重建索引:

In [127]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

如果想要改变广播方向, 在列上进行广播, 在行上匹配, 就必须使用算术方法的其中一种:

In [128]:
series3 = frame['d']

In [129]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [130]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [131]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 函数应用和映射

Numpy  的通用函数也可以用在  Pandas  上:

In [132]:
frame = pd.DataFrame(np.random.randn(4, 3), 
                     columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.716004  0.929323 -1.513708
Ohio    0.155595 -1.408729 -1.078987
Texas  -0.669757 -0.964958  0.620010
Oregon  0.274054  1.140951  0.728138

In [133]:
np.abs(frame)

b         d         e
Utah    0.716004  0.929323  1.513708
Ohio    0.155595  1.408729  1.078987
Texas   0.669757  0.964958  0.620010
Oregon  0.274054  1.140951  0.728138

另外一个常用功能是, 将函数应用到一行或者一列的一维数组上, 可以使用  `apply`  方法来实现这个功能:

In [134]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    0.990058
d    2.549680
e    2.241846
dtype: float64

In [135]:
frame.apply(f, axis='columns')

Utah      2.443031
Ohio      1.564324
Texas     1.584968
Oregon    0.866897
dtype: float64

大部分时候都是用内置的方法, 基本不需要自定义一个  `apply`

该函数也不一定是个标量, 也可以是  Series

In [136]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.716004 -1.408729 -1.513708
max  0.274054  1.140951  0.728138

调用  `applymap`  方法可以实现逐元素执行的方法：

In [137]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.72   0.93  -1.51
Ohio     0.16  -1.41  -1.08
Texas   -0.67  -0.96   0.62
Oregon   0.27   1.14   0.73

Series  有一个  `map`  方法, 功能是一致的

In [138]:
frame['e'].map(format)

Utah      -1.51
Ohio      -1.08
Texas      0.62
Oregon     0.73
Name: e, dtype: object

### 排序和排名

使用  `sort_index`  可以按需对行或者列索引进行字典序排序.

该方法返回一个新的, 排序好的对象:

In [139]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [140]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [141]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

同时也支持降序排序

In [142]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

如果希望根据值来排序, 那么需要使用  `sort_value`  方法:

In [143]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

默认情况下缺失值会被排序到最后:

In [144]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

对  DataFrame  排序时, 可以使用一列或者多列作为排序键:

In [145]:
frame = pd.DataFrame({'b': [4, 7, -3, -2], 
                      'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1 -2

In [146]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1 -2
0  0  4
1  1  7

In [147]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1 -2
1  1  7

`rank`  函数可以获取排名, 默认情况下, 当出现相同的标签是会用平均排名:

In [148]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

下面例子就是不使用平均排名的方式:

In [149]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

或者还可以降序排名:

In [150]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

改变平级关系的表:

DataFrame  也可以计算排名:

In [151]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2],
                      'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

### 含有重复标签的轴索引

虽然某些索引函数要求标签唯一, 但这并不是强制性的.

In [152]:
obj = pd.Series(range(5),
                index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [153]:
obj.index.is_unique

False

此时你去索引它, 他就会返回多条数据:

In [154]:
obj['a']

a    0
a    1
dtype: int64

In [155]:
obj['c']

4

在  DataFrame  中这个情况也是一样的

In [156]:
df = pd.DataFrame(np.random.randn(4, 3),
                  index=['a', 'a', 'b', 'b'])
df

0         1         2
a -1.713140  1.179365 -0.884410
a  1.207330 -0.344822 -0.894969
b  0.370657 -1.868140  1.167729
b -0.436507 -0.096494 -0.446741

In [157]:
df.loc['b']

0         1         2
b  0.370657 -1.868140  1.167729
b -0.436507 -0.096494 -0.446741

## 描述性统计的概述与计算

与  Numpy  内建的类似的方法相比, Pandas  增加了对缺失值的处理.

In [158]:
df = pd.DataFrame([[1.4, np.nan],
                   [7.1, -4.5],
                   [np.nan, np.nan],
                   [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

默认情况下, 返回的是列的加和情况, 并自动排除  NaN  值

In [159]:
df.sum()

one    9.25
two   -5.80
dtype: float64

指定轴后可以实现行加和.

In [160]:
df.sum(axis=1)

a    1.40
b    2.60
c     NaN
d   -0.55
dtype: float64

如果不希望排除缺失值, 可以指定  `skipna`  参数.

In [161]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

规约方法的可选参数:

一些方法返回的是间接统计信息:

In [162]:
df.idxmax()

one    b
two    d
dtype: object

除了规约方法, 还有积累型方法:

In [163]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

也有既不是积累型也不是规约型的方法.

`describe`  可以一次性产生多个汇总统计.

In [164]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

如果是非数值型数据, `describe`  会产生另一种汇总统计:

In [165]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

相关方法的完成列表:

### 相关性和协方差



In [168]:
price = pd.read_pickle('example/yahoo_price.pkl')
volume = pd.read_pickle('example/yahoo_volume.pkl')


计算股价百分比:

In [170]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

`corr`  计算的是相关性, 两个  Series  中重叠的, 非  NA  的, 按索引对齐的值.

对应的, `cov`  计算的是协方差.

In [171]:
returns['MSFT'].corr(returns['IBM'])

0.4997636114415116

In [172]:
returns['MSFT'].cov(returns['IBM'])

8.8706554797035475e-05

用更简洁的语法完成任务:

In [173]:
returns.MSFT.corr(returns.IBM)

0.4997636114415116

如果使用的是  DataFrame  返回的则是相关性和协方差矩阵.

In [174]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [175]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

`corrwith`  可以计算某一行或者列与其他序列的相关性.

In [176]:
returns.corrwith(returns.IBM)

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [177]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

### 唯一值 计数和成员属性


In [178]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [179]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

唯一值不是按顺序来进行的, 如果需要排序, 可以使用  `uniques.sort()`  .


In [180]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

顶层的  `value_counts`  也可以使用, 也用于任意数组或者序列:

In [181]:
pd.value_counts(obj.values, sort=False)

a    3
b    2
c    3
d    1
dtype: int64

`isin`  可以用作成员属性检查, 还可以将数据集以  Series  或  DataFrame  一列的形式过滤子集.

In [182]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [183]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [184]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

`Index.get_indexer`  可以将一个数组转换为另一个唯一值数组.

In [185]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

唯一值 计数和集合成员属性方法:

直方图统计:

In [186]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4,],
                     'Qu2': [2, 3, 1, 2, 3,],
                     'Qu3': [1, 5, 2, 4, 4,],})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [188]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0